# Generated by Django 5.1.3 on 2024-12-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watched_anime',
            field=models.JSONField(default=list),
        ),
    ]
